<?php

/**
 * @file
 * Primary module hooks for Bitrix Widget module.
 */

/**
 * Implements hook_theme().
 */
function bitrix_widget_theme($existing, $type, $theme, $path) {
  return [
    'bitrix_widget_button' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bitrix_widget_preprocess_html(&$variables) {
  $route = \Drupal::routeMatch()->getRouteObject();
  $is_admin_route = \Drupal::service('router.admin_context')->isAdminRoute($route);

  if ($is_admin_route) {
    return;
  }

  $state = \Drupal::state();
  $widget_status = $state->get('bitrix_widget_status');

  if ($widget_status) {
    $widget_code = $state->get('bitrix_widget_code');

    if (is_null($widget_code) || $widget_code === '') {
      return;
    }

    $variables['page_bottom']['bitrix_widget_button'] = [
      '#theme' => 'bitrix_widget_button',
      '#attached' => [
        'drupalSettings' => [
          'bitrix_widget_code' => $widget_code,
        ],
        'library' => [
          'bitrix_widget/bitrix-widget-button',
        ],
      ],
    ];
  }

  $variables['#cache']['tags'][] = 'bitrix_widget_settings';
}
